version: "3.3"

services:
  givgroov:
    container_name: givgroov
    image: registry.timosur.com/givgroov
    environment:
      VIRTUAL_HOST: givgroov.de
      LETSENCRYPT_HOST: givgroov.de
      LETSENCRYPT_EMAIL: info@givgroov.de
    expose:
      - 80
    networks:
      - jwilder

networks:
  jwilder:
    external:
      name: jwilder-proxy
